ARRAY CREATTIONS
    
    np.array()          # create array from list
    np.zeros()          # array of zeros
    np.ones()           # array of ones
    np.full()           # array filled with a value
    np.arange()         # evenly spaced values (like range)
    np.linspace()       # evenly spaced values (fixed count)
    np.eye()            # identity matrix
    np.random.rand()    # random array (0 to 1)
    np.random.randn()   # random array (normal distribution)
    np.random.randint() # random integers
    np.empty()          # uninitialized array (fast)

Importing numpy

In [20]:
import numpy as np

1. np.array() → Create array from list

In [21]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)       
print(type(arr)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>


2. np.zeros() → Array of zeros

In [22]:
zeros_arr = np.zeros((2, 3))

print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


3. np.ones() → Array of ones

In [23]:
ones_arr = np.ones((3, 3))

print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4. np.full() → Array filled with a value

In [24]:
full_arr = np.full((2, 2), 7)

print(full_arr)

[[7 7]
 [7 7]]


5. np.arange() → Evenly spaced values (like range)

In [25]:
arr_range = np.arange(10)

arr_step = np.arange(2, 10, 2)

print(arr_range)  
print(arr_step)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


6. np.linspace() → Fixed number of evenly spaced values

In [26]:
lin_arr = np.linspace(0, 1, 5)

print(lin_arr)

[0.   0.25 0.5  0.75 1.  ]


7. np.eye() → Identity matrix

In [27]:
identity = np.eye(3)

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. np.random.rand() → Random values (0 to 1)

In [28]:
rand_arr = np.random.rand(2, 2)

print(rand_arr)

[[0.54783206 0.57042594]
 [0.49588214 0.92698145]]


9. np.random.randn() → Normal distribution

In [29]:
randn_arr = np.random.randn(2, 3)

print(randn_arr)

[[ 0.99624596  1.94621768 -0.11611931]
 [ 0.67406351 -0.347627   -1.4964778 ]]


10. np.random.randint() → Random integers

In [30]:
randint_arr = np.random.randint(1, 10, size=5)

print(randint_arr)

[8 1 1 9 9]


11. np.empty() → Uninitialized array (⚡ very fast)

In [31]:
empty_arr = np.empty((2, 2))

print(empty_arr)

[[0.54783206 0.57042594]
 [0.49588214 0.92698145]]
