ARRAY RESHAPING & MANIPULATION
    
    pythonarr.reshape()       # change shape
    arr.flatten()       # collapse to 1D (copy)
    arr.ravel()         # collapse to 1D (view)
    arr.T               # transpose
    np.transpose()      # transpose with axis control
    np.expand_dims()    # add new dimension
    np.squeeze()        # remove single dimensions
    np.resize()         # resize array

In [15]:
import numpy as np

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


1. arr.reshape() → Change shape

In [17]:
reshaped = arr.reshape(2, 3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


2. arr.flatten() → Convert to 1D (COPY)


In [18]:
flat = reshaped.flatten()

print(flat)  

flat[0] = 100
print(reshaped) 

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


3. arr.ravel() → Convert to 1D (VIEW)

In [19]:
ravel_arr = reshaped.ravel()

print(ravel_arr)

ravel_arr[0] = 999
print(reshaped)  

[1 2 3 4 5 6]
[[999   2   3]
 [  4   5   6]]


4. arr.T → Transpose (quick)

In [20]:
matrix = arr.reshape(2, 3)

print(matrix.T)

[[999   4]
 [  2   5]
 [  3   6]]


5. np.transpose() → Advanced transpose

In [21]:
print(np.transpose(matrix))

arr3d = np.array([[[1,2],[3,4]]])

transposed = np.transpose(arr3d, (0, 2, 1))
print(transposed)

[[999   4]
 [  2   5]
 [  3   6]]
[[[1 3]
  [2 4]]]


6. np.expand_dims() → Add dimension

In [22]:
expanded = np.expand_dims(arr, axis=0)

print(expanded.shape)  

expanded_col = np.expand_dims(arr, axis=1)
print(expanded_col.shape)  

(1, 6)
(6, 1)


7. np.squeeze() → Remove single dimensions

In [23]:
arr2 = np.array([[[1, 2, 3]]])  # shape (1,1,3)

squeezed = np.squeeze(arr2)

print(squeezed.shape)  # (3,)


(3,)


8. np.resize() → Resize array

In [24]:
resized = np.resize(arr, (3, 4))

print(resized)

[[999   2   3   4]
 [  5   6 999   2]
 [  3   4   5   6]]
