MATH OPERATIONS
     
    np.add()            # addition
    np.subtract()       # subtraction
    np.multiply()       # multiplication
    np.divide()         # division
    np.power()          # exponentiation
    np.mod()            # modulus
    np.abs()            # absolute value
    np.sqrt()           # square root
    np.exp()            # e^x
    np.log()            # natural log
    np.log2()           # log base 2
    np.log10()          # log base 10
    np.floor()          # round down
    np.ceil()           # round up
    np.round()          # round to n decimals
    np.clip()           # limit values to a range  ← very useful

In [11]:
import numpy as np

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

In [13]:
result = np.add(a, b)
print(result)
result = np.subtract(b, a)
print(result) 
result = np.multiply(a, b)
print(result) 
result = np.divide(b, a)
print(result)
result = np.power(a, 2)
print(result)
result = np.mod(b, 3)
print(result) 
result = np.sqrt(a)
print(result) 
result = np.exp(a)
print(result)
result = np.log(a)
print(result)
result = np.log2(a)
print(result)
result = np.log10(a)
print(result)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 1  4  9 16]
[1 2 0 1]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [14]:
arr = np.array([-1, -5, 3, -10])

result = np.abs(arr)
print(result)

[ 1  5  3 10]


In [15]:
arr = np.array([1.9, 2.5, 3.1])

print(np.floor(arr))
print(np.ceil(arr)) 
print(np.round(arr))       
print(np.round(arr, 1))

[1. 2. 3.]
[2. 3. 4.]
[2. 2. 3.]
[1.9 2.5 3.1]


In [16]:
arr = np.array([5, 10, 15, 20, 25])

# Keep values between 10 and 20
clipped = np.clip(arr, 10, 20)

print(clipped)  #

[10 10 15 20 20]
