STATISTICS 
    
    np.mean()           # average
    np.median()         # middle value
    np.std()            # standard deviation
    np.var()            # variance
    np.min()            # minimum value
    np.max()            # maximum value
    np.sum()            # sum of elements
    np.cumsum()         # cumulative sum
    np.cumprod()        # cumulative product
    np.percentile()     # nth percentile     ← heavily used
    np.quantile()       # nth quantile
    np.corrcoef()       # correlation matrix ← very important
    np.cov()            # covariance matrix
    np.histogram()      # frequency distribution
    np.bincount()       # count occurrences
    np.unique()         # unique values + counts
    np.average()        # weighted average


In [10]:
import numpy as np

In [11]:
arr = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])

In [12]:
print(np.mean(arr))  
print(np.median(arr))  
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr2))
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.quantile(arr, 0.5)) 

30.0
30.0
14.142135623730951
200.0
10
50
150
[ 10  30  60 100 150]
[  1   2   6  24 120]
30.0
20.0
30.0


In [13]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print(np.corrcoef(x, y))
print(np.cov(x, y))

[[1. 1.]
 [1. 1.]]
[[  1.66666667  16.66666667]
 [ 16.66666667 166.66666667]]


In [14]:
data = np.array([1,2,2,3,3,3,4,4,5])

hist, bins = np.histogram(data, bins=3)

print(hist) 
print(bins) 

[3 3 3]
[1.         2.33333333 3.66666667 5.        ]


In [15]:
data = np.array([1, 2, 2, 3, 3, 3])

print(np.bincount(data))


[0 1 2 3]


In [16]:
data = np.array([1,2,2,3,3,3])

values, counts = np.unique(data, return_counts=True)

print(values)  
print(counts) 

[1 2 3]
[1 2 3]


In [17]:
values = np.array([10, 20, 30])
weights = np.array([1, 2, 3])

print(np.average(values, weights=weights))

23.333333333333332
