JOINING & SPLITTING
    
    np.concatenate()    # join arrays
    np.vstack()         # stack vertically (row-wise)
    np.hstack()         # stack horizontally (col-wise)
    np.stack()          # stack along new axis
    np.split()          # split into equal parts
    np.vsplit()         # split vertically
    np.hsplit()         # split horizontally
    np.append()         # append values

In [20]:
import numpy as np

In [21]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

1. np.concatenate() → Join arrays (flexible)

In [22]:
result = np.concatenate((a, b), axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
result = np.concatenate((a, b), axis=1)

print(result)

[[1 2 5 6]
 [3 4 7 8]]


2. np.vstack() → Vertical stack (row-wise)

In [24]:
result = np.vstack((a, b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


3. np.hstack() → Horizontal stack (column-wise)

In [25]:
result = np.hstack((a, b))

print(result)

[[1 2 5 6]
 [3 4 7 8]]


4. np.stack() → Stack along NEW axis 

In [28]:
result = np.stack((a, b), axis=0)

print(result.shape) 

(2, 2, 2)


SPLITTING ARRAYS

5. np.split() → Equal splits

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])

result = np.split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


6. np.vsplit() → Vertical split

In [31]:
arr2 = np.array([[1,2],
                 [3,4],
                 [5,6],
                 [7,8]])

result = np.vsplit(arr2, 2)
print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


7. np.hsplit() → Horizontal split

In [32]:
result = np.hsplit(arr2, 2)

print(result)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


➕ MODIFYING ARRAYS

8. np.append() → Append values

In [33]:
arr = np.array([1, 2, 3])

new_arr = np.append(arr, 4)
print(new_arr)

[1 2 3 4]


In [34]:
new_arr = np.append(arr, [5, 6])
print(new_arr) 

[1 2 3 5 6]
