SEARCHING & SORTING

    np.sort()           # sort array
    np.argsort()        # indices that would sort array ← useful
    np.argmax()         # index of max value
    np.argmin()         # index of min value
    np.where()          # conditional selection      ← very heavily used
    np.searchsorted()   # find insert position
    np.extract()        # extract elements by condition
    np.nonzero()   

In [1]:
import numpy as np

In [2]:
arr = np.array([40, 10, 30, 20, 50])

1. np.sort() → Sort array

In [3]:
sorted_arr = np.sort(arr)

print(sorted_arr) 

[10 20 30 40 50]


2. np.argsort() → Indices that sort array

In [4]:
indices = np.argsort(arr)

print(indices)  

[1 3 2 0 4]


3. np.argmax() → Index of max value

In [6]:
print(np.argmax(arr)) 

4


4. np.argmin() → Index of min value

In [8]:
print(np.argmin(arr))  

1


5. np.where() → Conditional selection (VERY IMPORTANT)

In [9]:
result = np.where(arr > 25)

print(result) 

(array([0, 2, 4]),)


In [10]:
new_arr = np.where(arr > 25, 1, 0)

print(new_arr)

[1 0 1 0 1]


6. np.searchsorted() → Find insert position

In [12]:
sorted_arr = np.array([10, 20, 30, 40])

In [13]:
pos = np.searchsorted(sorted_arr, 25)

print(pos)  

2


7. np.extract() → Extract elements by condition

In [15]:
result = np.extract(arr > 25, arr)

print(result)

[40 30 50]


8. np.nonzero() → Indices of non-zero elements

In [16]:
arr2 = np.array([0, 1, 0, 2, 3])

print(np.nonzero(arr2))

(array([1, 3, 4]),)
