LINEAR ALGEBRA (Core for ML)

    np.random.seed()        # reproducibility        ← always use
    np.random.rand()        # uniform distribution
    np.random.randn()       # normal distribution
    np.random.randint()     # random integers
    np.random.choice()      # random sample          ← very useful
    np.random.shuffle()     # shuffle in place
    np.random.permutation() # shuffled copy
    np.random.normal()      # normal dist with params
    np.random.uniform()     # uniform dist with params
    np.random.binomial()    # binomial distribution
    np.random.poisson()     # poisson distribution

In [14]:
import numpy as np

1. np.random.seed() → Reproducibility (VERY IMPORTANT)

In [15]:
np.random.seed(42)

print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


2. np.random.rand() → Uniform (0 to 1)

In [16]:
print(np.random.rand(2, 2))

[[0.59865848 0.15601864]
 [0.15599452 0.05808361]]


3. np.random.randn() → Standard Normal (mean=0, std=1)

In [17]:
print(np.random.randn(2, 3))

[[ 0.27904129  1.01051528 -0.58087813]
 [-0.52516981 -0.57138017 -0.92408284]]


4. np.random.randint() → Random integers

In [18]:
print(np.random.randint(1, 10, size=5))

[6 9 1 3 7]


 5. np.random.choice() → Random sampling

In [19]:
arr = np.array([10, 20, 30, 40])

print(np.random.choice(arr, size=2))

[40 40]


6. np.random.shuffle() → Shuffle in place

In [20]:
arr = np.array([1, 2, 3, 4])

np.random.shuffle(arr)

print(arr)  

[2 4 3 1]


7. np.random.permutation() → Shuffled copy

In [21]:
arr = np.array([1, 2, 3, 4])

new_arr = np.random.permutation(arr)

print(new_arr)  
print(arr)   

[2 1 4 3]
[1 2 3 4]


8. np.random.normal() → Normal distribution with params

In [22]:
print(np.random.normal(50, 10, 5))

[47.06600854 49.70161431 50.95125784 56.64654343 48.59781503]


9. np.random.uniform() → Uniform with range

In [23]:
print(np.random.uniform(5, 10, 5))

[6.15446913 6.20512733 8.41631759 8.04998329 9.16597456]


10. np.random.binomial() → Binomial distribution

In [24]:
print(np.random.binomial(10, 0.5, 5))

[4 5 4 6 5]


11. np.random.poisson() → Poisson distribution

In [25]:
print(np.random.poisson(3, 5))

[2 5 8 2 0]
