LINEAR ALGEBRA (Core for ML)

    np.dot()                # dot product            ← very heavily used
    np.matmul()             # matrix multiplication
    np.linalg.inv()         # matrix inverse
    np.linalg.det()         # determinant
    np.linalg.eig()         # eigenvalues/vectors    ← used in PCA
    np.linalg.svd()         # singular value decomp  ← used in PCA/ML
    np.linalg.norm()        # vector/matrix norm
    np.linalg.solve()       # solve linear equations
    np.linalg.rank()        # matrix rank
    np.cross()              # cross product

In [15]:
import numpy as np

In [16]:
# Sample Data
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

v = np.array([1, 2])


 1. np.dot() → Dot product (VERY IMPORTANT)

In [17]:
print(np.dot(v, v)) 

print(np.dot(A, B))

5
[[19 22]
 [43 50]]


2. np.matmul() → Matrix multiplication

In [18]:
print(np.matmul(A, B))

[[19 22]
 [43 50]]


3. np.linalg.inv() → Matrix inverse

In [19]:
inv_A = np.linalg.inv(A)

print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


4. np.linalg.det() → Determinant

In [20]:
print(np.linalg.det(A))

-2.0000000000000004


 5. np.linalg.eig() → Eigenvalues & eigenvectors

In [21]:
values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


 6. np.linalg.svd() → Singular Value Decomposition

In [22]:
U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("S:", S)
print("Vt:\n", Vt)

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S: [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


7. np.linalg.norm() → Vector / matrix norm

In [23]:
print(np.linalg.norm(v)) 

print(np.linalg.norm(A))

2.23606797749979
5.477225575051661


8. np.linalg.solve() → Solve linear equations

In [24]:
b = np.array([5, 6])

x = np.linalg.solve(A, b)

print(x)

[-4.   4.5]


9. np.linalg.rank() → Matrix rank

print(np.linalg.matrix_rank(A))

10. np.cross() → Cross product

In [25]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

print(np.cross(a, b)) 

[0 0 1]
