SAVING & LOADING DATA

    np.save()           # save array as .npy
    np.load()           # load .npy file
    np.savetxt()        # save as .txt or .csv
    np.loadtxt()        # load from .txt or .csv
    np.genfromtxt()     # load with missing value handling

In [10]:
import numpy as np

In [11]:
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

1. np.save() → Save as .npy (binary, fast)

In [12]:
np.save("data.npy", data)

2. np.load() → Load .npy

In [13]:
loaded = np.load("data.npy")

print(loaded)

[[1 2 3]
 [4 5 6]]


3. np.savetxt() → Save as text/CSV

In [14]:
np.savetxt("data.txt", data, delimiter=",")

4. np.loadtxt() → Load text/CSV

In [15]:
loaded = np.loadtxt("data.txt", delimiter=",")

print(loaded)

[[1. 2. 3.]
 [4. 5. 6.]]


5. np.genfromtxt() → Load with missing values

In [16]:
loaded = np.genfromtxt("data.txt", delimiter=",", filling_values=0)

print(loaded)

[[1. 2. 3.]
 [4. 5. 6.]]
